name: snake
description: A classic snake game

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_snake: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_native_splash: ^2.3.8
  icons_launcher: ^2.1.6
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/snake_icon.png
    - assets/snake_splash.png
    - assets/snake_android12_splash.png

icons_launcher:
  # dart run icons_launcher:create
  image_path: "assets/snake_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  # dart run flutter_native_splash:create
  color: "#1d1d1d"
  image: assets/snake_splash.png
  android_12:
    image: assets/snake_android12_splash.png
    color: "#1d1d1d"

  fullscreen: true
